"""add field is_published in posts table

Revision ID: 3b94886099d1
Revises: e1eaa0d0e56c
Create Date: 2026-05-26 11:26:49.518560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b94886099d1'
down_revision: Union[str, Sequence[str], None] = 'e1eaa0d0e56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_published', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_published')
    # ### end Alembic commands ###
