"""modify typo in primaryjoin of posts table

Revision ID: 6a5f0f9dc399
Revises: 3b94886099d1
Create Date: 2026-05-26 11:43:31.535855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5f0f9dc399'
down_revision: Union[str, Sequence[str], None] = '3b94886099d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
