"""add unique contaraint post_techs and post_section_images

Revision ID: e1eaa0d0e56c
Revises: 942333d7be6e
Create Date: 2026-05-23 21:21:34.134653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1eaa0d0e56c'
down_revision: Union[str, Sequence[str], None] = '942333d7be6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_post_section_image_post_section_id_image_id', 'post_section_images', ['post_section_id', 'image_id'])
    op.create_unique_constraint('uq_post_tech_post_id_tech_id', 'post_techs', ['post_id', 'tech_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_post_tech_post_id_tech_id', 'post_techs', type_='unique')
    op.drop_constraint('uq_post_section_image_post_section_id_image_id', 'post_section_images', type_='unique')
    # ### end Alembic commands ###
