"""modify relationships

Revision ID: ec3657478b91
Revises: 6a5f0f9dc399
Create Date: 2026-05-27 15:32:12.725328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import IntegrityError


# revision identifiers, used by Alembic.
revision: str = 'ec3657478b91'
down_revision: Union[str, Sequence[str], None] = '6a5f0f9dc399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_section_images')
    op.add_column('images', sa.Column('post_section_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'images', 'post_sections', ['post_section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'post_section_id')
    op.create_table('post_section_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_section_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('post_section_images_image_id_fkey')),
    sa.ForeignKeyConstraint(['post_section_id'], ['post_sections.id'], name=op.f('post_section_images_post_section_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('post_section_images_pkey')),
    sa.UniqueConstraint('post_section_id', 'image_id', name=op.f('uq_post_section_image_post_section_id_image_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
